language: node_js
node_js:
  - stable

install:
  - npm i -g typescript typings
  - npm install

before_script:
  - npm run build

script:
  - npm test

deploy:
  skip_cleanup: true
  provider: npm

  email: julien.sarazin@me.com
  api_key:
    secure: Gvp1xSmkWfB/y15M/qCMc+qUOhWEnFMgVCxaUcXAdSuv+ugF0teOgv8tlBX+wrvX6IGG5Qie/3ol6CyMMlN8fdKYSxpK+Jg0gGrcLaHPTyRfv922Z+WQcq1c1NunbjWPrMzwSkitnwHLKxRt5EkZJvjUY+lojJ0zQgh8iFXdfRF7s6bZVIJ/g9tiFEHOcP731dQSE5r8m5S0GaAqCO3Seixc1tPOeppE6jcVUaqM9mpoUDMozONHIWmVU6sJPbSSEpnSrfHqtL2HI05YsqTtzpu1BSnP+VdpDpIjFO7+Zmbv0Gnils4l8pS1gfDYeX8zLwbItSz3MHSEGhns8XJPVrmkSzO189R/dT1nwIsfiosjRKr9hpVoQGMBwdVsKh9mL5LbCX153Cc2fJxwrzto7BmIoiWAlq/n+oQS6GkzAYfdvbDW6MUbUmKhqWuYNtSVF86FGNmglID+fHVYZUkDVCfUGh1Db+Y5If9YR5RRtLQAAxZ2JS0jDCl/C5Y29ZWb2LerCxEVVGkKPqRauQDJWJz4vQb5NmbCvQ3tCroFZVp/T1Tvf2kEKFGI25ebEz5dxMuQUBazaS3a9O/2pwRbo+QGNMq2TlD6rQCeWPfFzet/ouUJJxMgCAnEqC0EP8AsVfpIKbBbB8vHSKgQYcxrLTZ4cjmZpVvv0gf3FncPbNY=
  on:
    tags: true
    repo: implicity-healthcare/nest-criteria
